### ISSUE TITLE
Issue with enabling module

### ISSUE THREAD

**Issue by vkuljak** [cerhardt/redcap-load-last-visit#1]
No matter what option I select and add branching logic to test, not one single field gets populated with previous data.
Please advise.
Thanks.

**Comment by mschulze0** [comment]
@vkuljak are you using it with repeating events?

**Comment by cerhardt** [comment]
@vkuljak sorry I did not get a notification about your issue. Did you resolve your problem?

**Comment by vkuljak** [comment]
Yes. Thanks.

**Comment by mschulze0** [comment]
@vkuljak how did you fix it?

**Comment by vkuljak** [comment]
It was an issue with one of the modules I have used, I disabled it and started working.

**Comment by mschulze0** [comment]
@vkuljak which module? I have the same issue so maybe I'm using the same module.

**Comment by vkuljak** [comment]
the redcap load last visit module; go under the modules and disable it.
