### ISSUE TITLE
usage with repeating events?

### ISSUE THREAD

**Issue by mschulze0** [cerhardt/redcap-load-last-visit#2]
Hi,

does this module work with repeating events? Doesn't do anything when I use it with them.

**Comment by soamyted** [comment]
Hi @mschulze0 did you get this to work with repeating events? I'm having the same issue!

**Comment by mschulze0** [comment]
@soamyted nope. Doesn't look like anyone is working on this module anymore.

**Comment by cerhardt** [comment]
@mschulze0 @soamyted sorry I've got no notification about your issue...  I'm still maintaining this module.

The module doesn't work for repeating events, just for longitudinal projects and repeating instances of forms as described.
